services:
  postgres:
    image: postgres
    container_name: bots-info-service-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: "bots"
    volumes:
      - botsinfoservicedb:/var/lib/postgresql/data
      - ./db:/docker-entrypoint-initdb.d
    ports:
      - "5434:5432"
    networks:
      - default
      - confbots-net

  bots-info-service:
    build: .
    container_name: "bots-info-service"
    environment:
      PORT: ${PORT}
      ENV: ${ENV}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    depends_on:
      - postgres
    networks:
      - default
      - confbots-net

volumes:
  botsinfoservicedb:

networks:
  confbots-net:
    external: true
